astra_db: 
  collection_name: "chatbotecom"

embedding_model:
  provider: "langchain"
  model_name: "all-MiniLM-L6-v2"

retriever:
  top_k: 3

llm:
  provider: "google"
  model_name: "gemini-1.5-pro"
